### PR TITLE
Use addOpener, registerOpener deprecated.

### PR DESCRIPTION
**Pull request by lexicalunit**

### CODE REVIEW

**Comment by mark-hahn** [comment]
Thanks for these.  I knew if I put it off long enough someone would do it
for me.  (grin)

**Comment by lexicalunit** [comment]
Spent the day making that deprecation cop as silent as possible. Still have 3 deprecations left, but they're in atom core so I think I'll just do the same as you and wait till those get patched out :)

**Comment by mark-hahn** [comment]
> making that deprecation cop as silent as possible.

It bothers me that there is no way to know when it is really empty.  The
errors only show when the deprecated code runs so you'd have to 100% test
coverage to see them all.

**Comment by mark-hahn** [comment]
Thanks again.

**Pull request merged**
